/* Generated By:JavaCC: Do not edit this line. ABC_compilerTreeConstants.java Version 5.0 */
package javapkg;

public interface ABC_compilerTreeConstants
{
  public int JJTROOT = 0;
  public int JJTDEFINE = 1;
  public int JJTMAINFUNCTION = 2;
  public int JJTBLOCK = 3;
  public int JJTFUNCTIONDEF = 4;
  public int JJTIFCONDITIONSTATEMENT = 5;
  public int JJTWHILECONDITIONSTATEMENT = 6;
  public int JJTCONDITION = 7;
  public int JJTBOOLVARIABLE = 8;
  public int JJTSTATEMENT = 9;
  public int JJTDECLARATION = 10;
  public int JJTVOID = 11;
  public int JJTIDLIST = 12;
  public int JJTCOPERATION = 13;
  public int JJTABCOPERATION = 14;
  public int JJTOBJECT = 15;
  public int JJTOBJECTNAME = 16;
  public int JJTACTION = 17;
  public int JJTACTIONNAME = 18;
  public int JJTACTIONPARAMS = 19;
  public int JJTEXPRESSION = 20;
  public int JJTEXPRESSION_P = 21;
  public int JJTEXPRESSION_P_NE = 22;
  public int JJTTERMOP = 23;
  public int JJTTERM = 24;
  public int JJTTERM_P = 25;
  public int JJTFACTOROP = 26;
  public int JJTFACTOR = 27;
  public int JJTVALUE = 28;
  public int JJTINTLITERALVALUE = 29;
  public int JJTDOUBLELITERALVALUE = 30;


  public String[] jjtNodeName = {
    "Root",
    "Define",
    "MainFunction",
    "Block",
    "FunctionDef",
    "IfConditionStatement",
    "WhileConditionStatement",
    "Condition",
    "BoolVariable",
    "Statement",
    "Declaration",
    "void",
    "IdList",
    "COperation",
    "ABCOperation",
    "Object",
    "ObjectName",
    "Action",
    "ActionName",
    "ActionParams",
    "Expression",
    "Expression_p",
    "Expression_p_ne",
    "TermOp",
    "Term",
    "Term_p",
    "FactorOp",
    "Factor",
    "Value",
    "IntLiteralValue",
    "DoubleLiteralValue",
  };
}
/* JavaCC - OriginalChecksum=663d6f6f2162c8b1205a5f628fba8c69 (do not edit this line) */
