/* Generated By:JJTree&JavaCC: Do not edit this line. ABC_compilerConstants.java */
package javapkg;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ABC_compilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEFINE = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int FUNC = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int DOUBLE = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int SELF_ADD = 18;
  /** RegularExpression Id. */
  int SELF_SUB = 19;
  /** RegularExpression Id. */
  int SELF_MUL = 20;
  /** RegularExpression Id. */
  int SELF_DIV = 21;
  /** RegularExpression Id. */
  int ADD = 22;
  /** RegularExpression Id. */
  int SUB = 23;
  /** RegularExpression Id. */
  int MUL = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int LE = 27;
  /** RegularExpression Id. */
  int MT = 28;
  /** RegularExpression Id. */
  int ME = 29;
  /** RegularExpression Id. */
  int EQ = 30;
  /** RegularExpression Id. */
  int NE = 31;
  /** RegularExpression Id. */
  int SEMI_COL = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int LBRACE = 35;
  /** RegularExpression Id. */
  int RBRACE = 36;
  /** RegularExpression Id. */
  int LPAR = 37;
  /** RegularExpression Id. */
  int RPAR = 38;
  /** RegularExpression Id. */
  int CAR = 39;
  /** RegularExpression Id. */
  int TEAM = 40;
  /** RegularExpression Id. */
  int FORWARD = 41;
  /** RegularExpression Id. */
  int BACK = 42;
  /** RegularExpression Id. */
  int ROTATE = 43;
  /** RegularExpression Id. */
  int MOVE_TO = 44;
  /** RegularExpression Id. */
  int BRAKE = 45;
  /** RegularExpression Id. */
  int WAIT = 46;
  /** RegularExpression Id. */
  int OBSTACLE = 47;
  /** RegularExpression Id. */
  int X = 48;
  /** RegularExpression Id. */
  int Y = 49;
  /** RegularExpression Id. */
  int DIR = 50;
  /** RegularExpression Id. */
  int SENSOR = 51;
  /** RegularExpression Id. */
  int REPORT = 52;
  /** RegularExpression Id. */
  int TEAM_ADD = 53;
  /** RegularExpression Id. */
  int TEAM_REMOVE = 54;
  /** RegularExpression Id. */
  int SENSOR_FIRE = 55;
  /** RegularExpression Id. */
  int SENSOR_LIGHT = 56;
  /** RegularExpression Id. */
  int SENSOR_SHAKE = 57;
  /** RegularExpression Id. */
  int SENSOR_PLANE = 58;
  /** RegularExpression Id. */
  int SENSOR_GAS = 59;
  /** RegularExpression Id. */
  int LETTER = 60;
  /** RegularExpression Id. */
  int DIGIT = 61;
  /** RegularExpression Id. */
  int FRAC = 62;
  /** RegularExpression Id. */
  int CHARACTER = 63;
  /** RegularExpression Id. */
  int ID = 64;
  /** RegularExpression Id. */
  int INT_NUM = 65;
  /** RegularExpression Id. */
  int DOUBLE_NUM = 66;
  /** RegularExpression Id. */
  int ERROR = 67;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"#define\"",
    "\"main\"",
    "\"void\"",
    "\"function\"",
    "\"int\"",
    "\"double\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"Car\"",
    "\"Team\"",
    "\"Forward\"",
    "\"Back\"",
    "\"Rotate\"",
    "\"MoveTo\"",
    "\"Brake\"",
    "\"Wait\"",
    "\"Obstacle\"",
    "\"x\"",
    "\"y\"",
    "\"dir\"",
    "\"Sensor\"",
    "\"Report\"",
    "\"add\"",
    "\"remove\"",
    "\"SENSOR_FIRE\"",
    "\"SENSOR_LIGHT\"",
    "\"SENSOR_SHAKE\"",
    "\"SENSOR_PLANE\"",
    "\"SENSOR_GAS\"",
    "<LETTER>",
    "<DIGIT>",
    "<FRAC>",
    "<CHARACTER>",
    "<ID>",
    "<INT_NUM>",
    "<DOUBLE_NUM>",
    "<ERROR>",
  };

}
