package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTAssignOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssignOperator extends SimpleNode {
  public ASTAssignOperator(int id) {
    super(id);
  }

  public ASTAssignOperator(ABC_compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=28947eab2beff41fa4ba4ba1d6dce55a (do not edit this line) */
