package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTActionName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTActionName extends SimpleNode {
  private int type;
  private String name;
  public ASTActionName(int id) {
    super(id);
  }

  public ASTActionName(ABC_compiler p, int id) {
    super(p, id);
  }

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
/* JavaCC - OriginalChecksum=aad1de88e1f001c40dbd7c2912ec49fd (do not edit this line) */
