package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTCOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCOperation extends SimpleNode {
  public ASTCOperation(int id) {
    super(id);
  }

  public ASTCOperation(ABC_compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9715b7c523fc9398ce40d0774d723465 (do not edit this line) */
