package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTDoubleLiteralValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDoubleLiteralValue extends SimpleNode {

  private double val;

  public ASTDoubleLiteralValue(int id) {
    super(id);
  }

  public ASTDoubleLiteralValue(ABC_compiler p, int id) {
    super(p, id);
  }

      public double getVal() {
        return val;
    }

    public void setVal(double val) {
        this.val = val;
    }

}
/* JavaCC - OriginalChecksum=e1843eeea24c9dbc35722a92388e7123 (do not edit this line) */
