package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTDefine.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDefine extends SimpleNode {
  public ASTDefine(int id) {
    super(id);
  }

  public ASTDefine(ABC_compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c511b17602698c43c056482acf181bd (do not edit this line) */
