package javapkg;

import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression extends SimpleNode {

	private String val;
    private int type;
	
  public ASTExpression(int id) {
    super(id);
  }

  public ASTExpression(ABC_compiler p, int id) {
    super(p, id);
  }

   public String getVal() {
        return val;
    }

    public void setVal(String val) {
        this.val = val;
    }
    
    public int getType() {
      return type;
    }

    public void setType(int type) {
        this.type=type;
    }

    public Sentence toSentence(ABC_compiler compiler) throws IOException {
      return new Sentence(compiler, type, val);
    }
}
/* JavaCC - OriginalChecksum=977d34b4c53e9f04f135097691984a1b (do not edit this line) */
