package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTFactorOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFactorOp extends SimpleNode {
  
  private int val;

  public ASTFactorOp(int id) {
    super(id);
  }

  public ASTFactorOp(ABC_compiler p, int id) {
    super(p, id);
  }

    public int getVal() {
        return val;
    }

    public void setVal(int val) {
        this.val = val;
    }

}
/* JavaCC - OriginalChecksum=d0f2d7920a4ac3afe3e29f7217c929e7 (do not edit this line) */
