package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTFactor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFactor extends SimpleNode {
  private String val;
  private int type;
  public ASTFactor(int id) {
    super(id);
  }

  public ASTFactor(ABC_compiler p, int id) {
    super(p, id);
  }

    public String getVal() {
        return val;
    }

    public void setVal(String val) {
        this.val = val;
    }
    
    public int getType() {
      return type;
    }

    public void setType(int type) {
        this.type=type;
    }
}
/* JavaCC - OriginalChecksum=38e7fb9dbb4bb9a759c92db83a3c14fc (do not edit this line) */
