package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTIntLiteralValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIntLiteralValue extends SimpleNode {

  private int val;

  public ASTIntLiteralValue(int id) {
    super(id);
  }

  public ASTIntLiteralValue(ABC_compiler p, int id) {
    super(p, id);
  }

    public int getVal() {
        return val;
    }

    public void setVal(int val) {
        this.val = val;
    }
}
/* JavaCC - OriginalChecksum=efcc1027cc453513f9894b3eaf023357 (do not edit this line) */
