package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTIdList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdList extends SimpleNode {
  public ASTIdList(int id) {
    super(id);
  }

  public ASTIdList(ABC_compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06ecc043c55945ecad216e5e02978589 (do not edit this line) */
