package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTMainFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainFunction extends SimpleNode {
  public ASTMainFunction(int id) {
    super(id);
  }

  public ASTMainFunction(ABC_compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec317400c29d3057332cf53412a107ba (do not edit this line) */
