package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTObject extends SimpleNode {
	private int name;
	private int objectId;
  public ASTObject(int id) {
    super(id);
  }

  public ASTObject(ABC_compiler p, int id) {
    super(p, id);
  }

	public int getName() {
		return name;
	}

	public void setName(int name) {
		this.name = name;
	}

	public int getObjectId() {
		return objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

}
/* JavaCC - OriginalChecksum=41376160b7b16206ce2d127c5b861a36 (do not edit this line) */
