package javapkg;

import java.io.IOException;

/* Generated By:JJTree: Do not edit this line. ASTStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement extends SimpleNode {
  private int statementType;

  private Command command;

  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(ABC_compiler p, int id) {
    super(p, id);
  }

  public void setStatementType(int statementType) {
    this.statementType = statementType;
  }

	public int getStatementType() {
		return statementType;
	}

	public Command getCommand() {
		return command;
	}

	public void setCommand(Command command) {
		this.command = command;
	}

	public Sentence toSentence(ABC_compiler compiler) throws IOException {
  	    return command.toSentence(compiler);
	}

}
/* JavaCC - OriginalChecksum=518e2defb2f9da964a930bf55dbf5a40 (do not edit this line) */
