package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTTermOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTermOp extends SimpleNode {

	 private int val;

  public ASTTermOp(int id) {
    super(id);
  }

  public ASTTermOp(ABC_compiler p, int id) {
    super(p, id);
  }

      public int getVal() {
        return val;
    }

    public void setVal(int val) {
        this.val = val;
    }
}
/* JavaCC - OriginalChecksum=b8df85f0b5256be52919b5924604050b (do not edit this line) */
