package javapkg;

/* Generated By:JJTree: Do not edit this line. ASTValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTValue extends SimpleNode {
	private String val;
  private int type;

  public ASTValue(int id) {
    super(id);
  }

  public ASTValue(ABC_compiler p, int id) {
    super(p, id);
  }

    public String getVal() {
        return val;
    }

    public void setVal(String val) {
        this.val = val;
    }
    
    public int getType() {
      return type;
    }

    public void setType(int type) {
        this.type=type;
    }
}
/* JavaCC - OriginalChecksum=8e2bccb9493c1bd279354421aa25bfbf (do not edit this line) */
