package javapkg;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SimpleNode implements Node {

  protected int id;
  protected Node parentNode;
  @Expose
  protected String name;
  @Expose
  @SerializedName("parent")
  protected String parentName;
  @Expose
  protected Node[] children;
  protected Object value;
  protected ABC_compiler parser;

  public SimpleNode(int i) {
    id = i;
    name = getClass().getCanonicalName().substring(8);
  }

  public SimpleNode(ABC_compiler p, int i) {
    this(i);
    parser = p;
     name = getClass().getCanonicalName();
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  @Override
  public String getNodeName() {
  	return name;
  }

  public void jjtSetParent(Node n) {
  	parentNode = n;
	  SimpleNode fa = (SimpleNode) parentNode;
	  parentName = fa.getNodeName();
  }
  public Node jjtGetParent() { return parentNode; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() { return ABC_compilerTreeConstants.jjtNodeName[id]; }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }
  }
}

/* JavaCC - OriginalChecksum=297e76478e5ee91110464f39d743707e (do not edit this line) */
